### ISSUE TITLE
Exception when opening schedule

### ISSUE THREAD

**Issue by zyuiop** [Susanfe/sdp-event-management#52]
Exception when opening the schedule:
```E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: ch.epfl.sweng.eventmanager, PID: 14748
                  java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.vipulasri.timelineview.TimelineView.initLine(int)' on a null object reference
                      at ch.epfl.sweng.eventmanager.ui.schedule.TimeLineViewHolder.<init>(TimeLineViewHolder.java:32)
                      at ch.epfl.sweng.eventmanager.ui.schedule.TimeLineAdapter.onCreateViewHolder(TimeLineAdapter.java:44)
                      at ch.epfl.sweng.eventmanager.ui.schedule.TimeLineAdapter.onCreateViewHolder(TimeLineAdapter.java:23)
                      at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6794)
                      at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5975)
                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
                      at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
                      at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
                      at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
                      at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
                      at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
                      at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
                      at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4194)
                      at android.view.View.layout(View.java:20672)
                      at android.view.ViewGroup.layout(ViewGroup.java:6194)
                      at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
                      at android.view.View.layout(View.java:20672)
                      at android.view.ViewGroup.layout(ViewGroup.java:6194)
                      at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1183)
                      at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:870)
                      at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:889)
                      at android.view.View.layout(View.java:20672)
                      at android.view.ViewGroup.layout(ViewGroup.java:6194)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                      at android.view.View.layout(View.java:20672)
                      at android.view.ViewGroup.layout(ViewGroup.java:6194)
                      at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:444)
                      at android.view.View.layout(View.java:20672)
                      at android.view.ViewGroup.layout(ViewGroup.java:6194)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                      at android.view.View.layout(View.java:20672)
                      at android.view.ViewGroup.layout(ViewGroup.java:6194)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
                      at android.view.View.layout(View.java:20672)
                      at android.view.ViewGroup.layout(ViewGroup.java:6194)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                      at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
                      at android.view.View.layout(View.java:20672)
                      at android.view.ViewGroup.layout(ViewGroup.java:6194)
                      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2792)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2319)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:761)
                      at android.view.Choreographer.doFrame(Choreographer.java:696)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
                      at android.os.Handler.handleCallback(Handler.java:873)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:193)
                      at android.app.ActivityThread.main(ActivityThread.java:6669)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)```

**Comment by Luminilion** [comment]
Working on it right after the meeting.

**Comment by vquelque** [comment]
Fixed Issue. Butterknife annotation processor was missing in graddle which would prevent butterknife from generating boilerplate binding code
